#!/usr/bin/python
# simple http request (header values)

import sys
import httplib
import urllib

from urlparse import urlparse



def getToken():
  endpoint = "https://charon.iplantcollaborative.org"
  o = urlparse(endpoint)

  path = "/auth"
  username = sys.argv[1]
  password = sys.argv[2]
	
  method = "GET"
  params = None
  headers = {
    "Content-type" : "application/x-www-form-urlencoded",
    "Accept" : "text/plain",
    "X-Auth-User" : username,
    "X-Auth-Key" : password
   }
  conn = httplib.HTTPSConnection(o.netloc,443)
  conn.request(method,path,params,headers)
  r1 = conn.getresponse()

  #print r1.read()
  print "HTTP RETURN CODE: %i, %s" % (r1.status,r1.reason)
  headers = r1.getheaders()
  conn.close()

  url = token = None

  for header in headers:
    if header[0] == "x-server-management-url" :
      url = header[1]
    if header[0] == "x-auth-token" :
      token = header[1]
  
  return url, token

print getToken()
