#!/usr/bin/python
# simple http request (header values)


import httplib
import urllib

url = "150.135.78.195"
port = 8000
path = "/auth"
username = "username"
password = "password"
method = "GET"
params = None
headers = {
        "Content-type" : "application/x-www-form-urlencoded",
        "Accept" : "text/plain",
        "X-Auth-User" : username,
        "X-Auth-Key" : password
        }



conn = httplib.HTTPConnection(url,port)
conn.request(method,path,params,headers)
r1 = conn.getresponse()

#print r1.read()
print "HTTP RETURN CODE: %i, %s" % (r1.status,r1.reason)
headers = r1.getheaders()
conn.close()

for header in headers:
	if header[0] == "x-server-management-url" :
		print header[1]
	if header[0] == "x-auth-token" :
		print header[1]

