Ext.BLANK_IMAGE_URL="/site_media/images/1x1t.gif";sessionStorage.clear();
require(["/site_media/scripts/utils/ajax_common_gateway.js"],function(){ajax_common_gateway("getUserProfile","GET","",function(){for(var b in JSON.parse(sessionStorage.getItem("__getUserProfile")).result.value){a=JSON.parse(sessionStorage.getItem("__getUserProfile")).result.value[b];for(var c in a)a.hasOwnProperty(c)&&sessionStorage.setItem(c,a[c])}ajax_common_gateway("getAppList","GET","",function(){require(["/site_media/scripts/north.js","/site_media/scripts/south.js","/site_media/scripts/east.js",
"/site_media/scripts/west.js","/site_media/scripts/center.js","/site_media/scripts/euca_actions.js","/site_media/scripts/utils/sessionStorageDebugger.js"],function(){init()})})})});var resource_request_jsonstore={},active_module_array=[],Active_module=function(){};Active_module.prototype.add=function(b){for(var c=0;c<active_module_array.length;c++)b===active_module_array[c]&&(b=null);b!==null&&active_module_array.push(b)};Active_module.prototype.remove=function(){};
Active_module.prototype.search=function(){};
var active_module=new Active_module,Instance_grid=function(){var b=new Ext.data.JsonStore({fields:["instance_name","instance_description","instance_tags","reservation_id","reservation_owner_id","group_id","instance_id","instance_image_id","instance_image_name","instance_public_dns_name","instance_private_dns_name","instance_state","instance_key_name","instance_ami_launch_index","instance_product_codes","instance_instance_type","instance_launch_time","instance_placement","instance_kernel","instance_ramdisk"],
root:""});this.init=function(){b.loadData({});new Ext.grid.GridPanel({renderTo:"running_instances_index",frame:!1,autoHeight:!0,viewConfig:{forceFit:!0},border:!1,store:b,columns:[{header:"Name",dataIndex:"instance_name",width:130,sortable:!0},{header:"Description",dataIndex:"instance_description",width:300,sortable:!0},{header:"Tags",dataIndex:"instance_tags",width:100,sortable:!0,hidden:!0},{header:"Researvation",dataIndex:"reservation_id",width:100,sortable:!0,hidden:!0},{header:"Owner id",dataIndex:"reservation_owner_id",
width:100,sortable:!0,hidden:!0},{header:"Group id",dataIndex:"group_id",width:100,sortable:!0,hidden:!0,hidden:!0},{header:"Instance id",dataIndex:"instance_id",width:100,sortable:!0},{header:"Machine Image Name",dataIndex:"instance_image_name",width:100,sortable:!0},{header:"Machine Image",dataIndex:"instance_image_id",width:100,sortable:!0},{header:"Public dns name",dataIndex:"instance_public_dns_name",width:100,sortable:!0},{header:"Private dns name",dataIndex:"instance_private_dns_name",width:100,
sortable:!0,hidden:!0},{header:"Key name",dataIndex:"instance_key_name",width:100,sortable:!0},{header:"State",dataIndex:"instance_state",width:100,sortable:!0},{header:"Ami index",dataIndex:"instance_ami_launch_index",width:100,sortable:!0,hidden:!0},{header:"P.Codes",dataIndex:"instance_product_code",width:100,sortable:!0,hidden:!0},{header:"Machine size",dataIndex:"instance_instance_type",width:100,sortable:!0},{header:"Launch Time",dataIndex:"instance_launch_time",width:100,sortable:!0},{header:"Placement",
dataIndex:"instance_placement",width:100,sortable:!0,hidden:!0},{header:"Kernel",dataIndex:"instance_kernel",width:100,sortable:!0,hidden:!0},{header:"Ramdisk",dataIndex:"instance_ramdisk",width:100,sortable:!0,hidden:!0}]})};this.update=function(c){active_module.add("center.dashboard.instance_grid");b.loadData(c==null?resource_request_jsonstore.getInstanceList:c)}},Machine_image_grid=function(){var b=new Ext.data.JsonStore({fields:["image_name","image_description","image_tags","image_id","image_location",
"image_ownerid","image_state","image_is_public","image_product_codes","image_architecture","image_type","image_ramdisk_id","image_kernel_id"],root:""});this.init=function(){b.loadData({});new Ext.grid.GridPanel({renderTo:"machine_images_management",frame:!1,autoHeight:!0,viewConfig:{forceFit:!0},border:!1,store:b,columns:[{header:"Name",dataIndex:"image_name",width:180,sortable:!0},{header:"Description",dataIndex:"image_description",width:350,sortable:!0},{header:"Image id",dataIndex:"image_id",width:150,
sortable:!0},{header:"Location",dataIndex:"image_location",width:300,sortable:!0,hidden:!0},{header:"Owner id",dataIndex:"image_ownerid",width:100,sortable:!0},{header:"Privilege",dataIndex:"image_is_public",width:70,sortable:!0},{header:"State",dataIndex:"image_state",width:100,sortable:!0},{header:"Code",dataIndex:"image_product_codes",width:100,sortable:!0,hidden:!0},{header:"Arch",dataIndex:"image_architecture",width:100,sortable:!0,hidden:!0},{header:"Type",dataIndex:"image_type",width:100,sortable:!0,
hidden:!0},{header:"Ramdisk",dataIndex:"image_ramdisk_id",width:100,sortable:!0,hidden:!0},{header:"Kernel",dataIndex:"image_kernel_id",width:100,sortable:!0,hidden:!0},{header:"Tags",dataIndex:"image_tags",width:120,sortable:!0}]})};this.update=function(c){active_module.add("center.dashboard.machine_image_grid");b.loadData(c==null?resource_request_jsonstore.getImageList:c)}},Volume_storage_grid=function(){var b=new Ext.data.JsonStore({fields:["no","name","description","tags","id","size","snapshot_id",
"status","create_time","attach_data_instance_id","attach_data_device","attach_data_attach_time"],root:""});this.init=function(){add_new_volume_form=new Ext.form.FormPanel({monitorValid:!0,width:425,frame:!0,items:[new Ext.form.TextField({id:"name",fieldLabel:"Name",width:275,allowBlank:!1}),new Ext.form.TextArea({id:"description",fieldLabel:"Description",width:275,height:40}),new Ext.form.TextField({id:"tags",fieldLabel:"Tags",width:275}),new Ext.form.TextField({id:"size",fieldLabel:"Size (G)",width:40,
allowBlank:!1,regex:/^0*[1-9][0-9]*$/})],buttons:[{text:"Create",formBind:!0,handler:function(){create_volume(add_new_volume_form.getForm().getValues().name,add_new_volume_form.getForm().getValues().description,add_new_volume_form.getForm().getValues().tags,add_new_volume_form.getForm().getValues().size)}}],buttonAlign:"center"});add_new_volume_form.render("volume_storage_management");b.loadData({});new Ext.grid.GridPanel({renderTo:"volume_storage_management",frame:!1,autoHeight:!0,viewConfig:{forceFit:!0},
border:!1,store:b,bodyStyle:"margin-top:5px",columns:[{header:"No",dataIndex:"no",width:25,sortable:!0},{header:"Name",dataIndex:"name",width:130,sortable:!0},{header:"Description",dataIndex:"description",width:300,sortable:!0},{header:"Tags",dataIndex:"tags",width:90,sortable:!0,hidden:!0},{header:"Volume id",dataIndex:"id",width:90,sortable:!0},{header:"size(G)",dataIndex:"size",width:50,sortable:!0},{header:"Snapshot id",dataIndex:"snapshot_id",width:100,sortable:!0,hidden:!0},{header:"Status",
dataIndex:"status",width:80,sortable:!0},{header:"Create Time",dataIndex:"create_time",width:150,sortable:!0},{header:"&raquo; Intance id",dataIndex:"attach_data_instance_id",width:100,sortable:!0},{header:"&raquo; Device",dataIndex:"attach_data_device",width:60,sortable:!0},{header:"&raquo; Attached time",dataIndex:"attach_data_attach_time",width:150,sortable:!0}]})};this.update=function(c){active_module.add("center.dashboard.volume_storage_grid");b.loadData(c==null?resource_request_jsonstore.getVolumeList:
c)}},Keys_grid=function(){var b=new Ext.data.JsonStore({fields:["keypair_name","keypair_fingerprint"],root:""});this.init=function(){b.loadData({});add_new_key_form=new Ext.form.FormPanel({labelWidth:80,frame:!0,layout:"column",bodyStyle:"padding:1px 1px 1px 1px",width:400,defaults:{width:250},defaultType:"textfield",items:[{fieldLabel:"Key pair name",name:"key_pair_name",allowBlank:!1},new Ext.Button({text:"Issue",boxMaxWidth:40,handler:function(){Ext.util.Format.trim(add_new_key_form.getForm().getValues().key_pair_name)!=
""?issue_new_key(add_new_key_form.getForm().getValues().key_pair_name):Ext.MessageBox.alert("Notce","Key name cannot be blank or spaces")}})]});add_new_key_form.render("authentication_keys_management");new Ext.grid.GridPanel({renderTo:"authentication_keys_management",frame:!1,autoHeight:!0,bodyStyle:"margin-top:5px",viewConfig:{forceFit:!0},border:!1,store:b,columns:[{header:"Keypair name",dataIndex:"keypair_name",width:100,sortable:!0},{header:"Keypair fingerprint",dataIndex:"keypair_fingerprint",
width:300,sortable:!0},{header:"Action",dataIndex:"keypair_name",width:85,sortable:!1,renderer:function(b){return'<input type="image" src="/site_media/images/cross.png" width="12" alt="Remove" id="delKey" keyname="'+b+'" onClick="removeKey(\''+b+"')\"/>"}}]})};this.update=function(c){active_module.add("center.dashboard.keys_grid");b.loadData(c==null?resource_request_jsonstore.getKeyPairsList:c)}},removeKey_post=function(){ajax_common_gateway("getKeyPairsList","GET","",function(){Ext.get("keys_tree").select("*").remove();
ajax_common_gateway("getKeyPairsListTree","GET","",west.foo);ajax_common_gateway("getKeyPairsList","GET","",keys_grid.update)})},issue_new_key=function(b){add_new_key_form.getForm().reset();var b="keypair_name="+b,c=new Ext.LoadMask(Ext.getBody(),{msg:"Creating your new key. Please wait..."});c.show();ajax_common_gateway("createKeyPair","POST",b,function(){c.hide();Ext.get("keys_tree").select("*").remove();ajax_common_gateway("getKeyPairsListTree","GET","",west.foo);show_key()})},show_key=function(){tem=
resource_request_jsonstore.createKeyPair.split("-----B");key_msg="<pre>-----B"+tem[1]+"</pre>";Ext.MessageBox.minWidth=500;Ext.MessageBox.alert("Your root key",key_msg);ajax_common_gateway("getKeyPairsListTree","GET","",keys_grid.update);ajax_common_gateway("getKeyPairsList","GET","",keys_grid.update)},keys_grid={a:"b"},init=function(){ajax_common_gateway("getVolumeList","GET","",function(){});new Ext.Viewport({layout:"border",items:[north.init,south.init,west.init,center(),east.init]});new west.cloud_instances;
new west.machine_images;new west.machine_volumes;new west.authentication_keys;new Launch_new_instance;instance_grid=new Instance_grid;instance_grid.init();machine_image_grid=new Machine_image_grid;machine_image_grid.init();volume_storage_grid=new Volume_storage_grid;volume_storage_grid.init();keys_grid=new Keys_grid;keys_grid.init();faye_communicator()},faye_communicator=function(){server="http://"+window.location.host+":9000/bayeux";channel="/"+sessionStorage.getItem("userid");(new Faye.Client(server,
{timeout:120})).subscribe(channel,function(b){notice.msg("Notice",b.msg)})},notice=function(){var b;return{msg:function(c,d){console.log(d);b||(b=Ext.DomHelper.insertFirst(document.body,{id:"msg-div"},!0));b.alignTo(document,"t-t");var e=String.format.apply(String,Array.prototype.slice.call(arguments,1));Ext.DomHelper.append(b,{html:['<div class="msg"><div class="x-box-ml"><div class="x-box-mr"><div class="x-box-mc"><h3>',c,"</h3>",e,'</div></div></div><div class="x-box-bl"><div class="x-box-br"><div class="x-box-bc"></div></div></div></div>'].join("")},
!0).slideIn("t").pause(4.3).ghost("t",{remove:!0})}}}();
