var Launch_new_instance=function(){active_module.add("center.dashboard.launch_new_instance");var b=new Ext.data.JsonStore({fields:["image_name","image_description","image_tags","image_id","image_location","image_ownerid","image_state","image_is_public","image_product_codes","image_architecture","image_type","image_ramdisk_id","image_kernel_id",{name:"aa",mapping:'image_id + " (" + obj.image_name + ")" '}],root:"",data:[{}]}),d=new Ext.data.JsonStore({fields:["name","cpus","memory","disc",{name:"aa",
mapping:'name + " (Cpu: " + obj.cpus + ", Mem: " + obj.memory + "M, Disk: " + obj.disc + "G)" '}],root:"",data:[{}]}),e=new Ext.data.JsonStore({fields:["keypair_name","keypair_fingerprint"],root:"",data:[{}]});(new Ext.data.JsonStore({fields:["no","id","size","snapshot_id","status","create_time","attach_data_instance_id","attach_data_device","attach_data_attach_time"],root:"",data:[{}]})).addListener("expand",function(){alert("ss")});var f=new Ext.form.ComboBox({store:b,fieldLabel:"Image id",hiddenName:"image_id",
displayField:"aa",valueField:"image_id",typeAhead:!0,mode:"local",triggerAction:"all",emptyText:"Select image...",selectOnFocus:!0,editable:!1,allowBlank:!1});f.addListener("expand",function(){var c=new Ext.LoadMask(Ext.getBody(),{msg:"Loading Image Catalog. Please wait..."});c.show();ajax_common_gateway("getImageList","GET","",function(){c.hide();b.loadData(resource_request_jsonstore.getImageList)})});var g=new Ext.form.ComboBox({store:d,fieldLabel:"Instance size",hiddenName:"instance_size",displayField:"aa",
valueField:"name",typeAhead:!0,mode:"local",triggerAction:"all",emptyText:"Select instance size...",selectOnFocus:!0,vtyle:"email",editable:!1,allowBlank:!1});g.addListener("expand",function(){ajax_common_gateway("getVmTypes","GET","",function(){d.loadData(resource_request_jsonstore.getVmTypes)})});var h=new Ext.form.ComboBox({store:e,fieldLabel:"Authentication key",hiddenName:"auth_key",displayField:"keypair_name",typeAhead:!0,mode:"local",triggerAction:"all",emptyText:"Select auth key...",selectOnFocus:!0,
editable:!1,allowBlank:!0});h.addListener("expand",function(){var b=new Ext.LoadMask(Ext.getBody(),{msg:"Loading your key info. Please wait..."});b.show();ajax_common_gateway("getKeyPairsList","GET","",function(){b.hide();e.loadData(resource_request_jsonstore.getKeyPairsList)})});var i=new Ext.form.TextArea({fieldLabel:"Description",name:"instance_description",selectOnFocus:!0,height:120}),c=new Ext.FormPanel({labelWidth:120,frame:!0,title:"Create new instance",method:"POST",bodyStyle:"padding:5px 5px 0",
width:470,defaults:{width:300},defaultType:"textfield",items:[{fieldLabel:"Instance name",name:"instance_name",allowBlank:!1},f,g,h,{fieldLabel:"Number of instances",name:"num_of_instances",emptyText:"1"},{fieldLabel:"Lifetime (Hours)",name:"instance_lifetime",emptyText:"0"},i,{fieldLabel:"Tags (Comma separated)",name:"instance_tags"}],buttons:[{text:"Launch",handler:function(){if(c.getForm().isValid()){auth_key=c.getForm().getFieldValues().auth_key;image_id=c.getForm().getFieldValues().image_id;
instance_description=c.getForm().getFieldValues().instance_description;inatance_name=c.getForm().getFieldValues().instance_name;instance_size=c.getForm().getFieldValues().instance_size;instance_lifetime=c.getForm().getFieldValues().instance_lifetime;instance_tags=c.getForm().getFieldValues().instance_tags;num_of_instances=c.getForm().getFieldValues().num_of_instances;var b=new Ext.LoadMask(Ext.getBody(),{msg:"Launching your VM. Please wait..."});b.show();ajax_common_gateway("launchInstance","POST",
c.getForm().getFieldValues(),success_callback_function=function(){Ext.MessageBox.alert("Status","Instance booting succeed.<br/>Please wait a few minutes to access. [code1]");b.hide();c.getForm().reset()},fail_callback_function=function(){b.hide();c.getForm().reset();a=JSON.parse(sessionStorage.getItem("__launchInstance")).result.value;Ext.MessageBox.alert("Message","<b><font color='#408080'>Your quota is over.</font></b><br/>Current resource use: "+a.current_cpu+" cpu, "+a.current_mem+"M mem<br/>Quota : "+
a.limit_cpu+" cpu, "+a.limit_mem+"M mem")})}else Ext.MessageBox.alert("Alert","Invalid Inputs")}}]});c.render("launch_new_instance")},detachVolume=function(b){instance_id=b.id.substring(14);b=b.id.substring(14)+"_selected_volume_detach";selected_volume=document.getElementById(b).value;Ext.Ajax.request({url:"/resource_request/detachVolume",method:"POST",params:{instance_id:instance,volume_id:selected_volume},success:function(){Ext.MessageBox.alert("Notice","Detached")},failure:function(){Ext.MessageBox.alert("Failed",
"Detaching failed")}})},create_volume=function(b,d,e,f){param="size="+f+"&name="+b+"&description="+d+"&tags="+e;ajax_common_gateway("createVolume","POST",param,success_callback_function=function(){console.log(sessionStorage.getItem("__createVolume"));console.log(eval("("+sessionStorage.getItem("__createVolume")+")").result.value[0]);Ext.MessageBox.alert("Alert","Volume "+eval("("+sessionStorage.getItem("__createVolume")+")").result.value[0]+" was created.");add_new_volume_form.getForm().reset()},
fail_callback_function=function(){console.log("create_volume_failed");console.log(m);Ext.MessageBox.alert("Failed","Not attached. Not valid volume")})},attachVolume=function(b){selected_volume=document.getElementById((b.id+"_selected_volume").substring(15)).value;b="selected_device_"+b.id.substring(15);selected_device=document.getElementById(b).value;Ext.Ajax.request({url:"/resource_request/attachVolume",method:"POST",params:{instance_id:instance,volume_id:selected_volume,device:selected_device},
success:function(){Ext.MessageBox.alert("Alert","Attached!")},failure:function(){Ext.MessageBox.alert("Failed","Not attached. Not valid volume")}})},removeKey=function(b){ajax_common_gateway("removeKeyPair","POST","keypair_name="+b,removeKey_post)};
