var west={};
west.init={region:"west",id:"west-panel",title:"Resources Index",split:!0,width:200,minSize:175,maxSize:400,collapsible:!0,collapsed:!0,margins:"0 0 0 5",layout:{type:"accordion",animate:!0},items:[{contentEl:"instances_tree",title:"Cloud Instances",html:"",border:!1,iconCls:"nav",listeners:{beforeexpand:function(){Ext.get("instances_tree").select("*").remove();new west.cloud_instances}}},{contentEl:"images_tree",title:"Machine Images",html:"",border:!1,iconCls:"settings",listeners:{beforeexpand:function(){Ext.get("images_tree").select("*").remove();new west.machine_images}}},
{contentEl:"volumes_tree",title:"Machine Volumes",html:"",border:!1,iconCls:"settings",listeners:{beforeexpand:function(){Ext.get("volumes_tree").select("*").remove();new west.machine_volumes}}},{contentEl:"snapshots_tree",title:"Snapshots",html:"",border:!1,iconCls:"settings",listeners:{beforeexpand:function(){Ext.get("volumes_tree").select("*").remove();new west.machine_volumes}}},{contentEl:"keys_tree",title:"Authentication Keys",html:"",border:!1,iconCls:"settings",listeners:{beforeexpand:function(){Ext.get("keys_tree").select("*").remove();
ajax_common_gateway("getKeyPairsListTree","GET","",west.foo)}}}]};
west.cloud_instances=function(){ajax_common_gateway("getRunningInstancesTree","GET","",function(a){a=a==null?resource_request_jsonstore.getRunningInstancesTree:a;this.tree=new Ext.tree.TreePanel({loader:new Ext.tree.TreeLoader,width:200,height:400,rootVisible:!1,border:!1,el:"instances_tree",id:"instanceTree",root:new Ext.tree.AsyncTreeNode({expanded:!0,leaf:!1,text:"Tree Root",children:a}),listeners:{click:function(a){center_panel_object.createTab(this.el,a.attributes.text)}}});this.tree.render()})};
west.machine_images=function(){render=function(a){a=a==null?resource_request_jsonstore.getMachineImageTree:a;this.tree=new Ext.tree.TreePanel({loader:new Ext.tree.TreeLoader,width:200,height:400,rootVisible:!1,border:!1,id:"imagesTree",renderTo:Ext.get("images_tree"),root:new Ext.tree.AsyncTreeNode({expanded:!0,leaf:!1,text:"Tree Root",children:a}),listeners:{click:function(a){center_panel_object.createTab(this.el,a.attributes.text)}}})};ajax_common_gateway("getMachineImageTree","GET","",render)};
west.machine_volumes=function(){ajax_common_gateway("getVolumeListTree","GET","",function(a){a=a==null?resource_request_jsonstore.getVolumeListTree:a;this.tree=new Ext.tree.TreePanel({loader:new Ext.tree.TreeLoader,width:200,height:400,rootVisible:!1,border:!1,id:"volumesTree",renderTo:Ext.get("volumes_tree"),root:new Ext.tree.AsyncTreeNode({expanded:!0,leaf:!1,text:"Tree Root",children:a}),listeners:{click:function(a){center_panel_object.createTab(this.el,a.attributes.text)}}})})};
west.authentication_keys=function(){ajax_common_gateway("getKeyPairsListTree","GET","",function(a){a=a==null?resource_request_jsonstore.getKeyPairsListTree:a;this.tree=new Ext.tree.TreePanel({loader:new Ext.tree.TreeLoader,width:200,height:300,rootVisible:!1,border:!1,renderTo:Ext.get("keys_tree"),root:new Ext.tree.AsyncTreeNode({expanded:!0,leaf:!1,text:"Tree Root",children:a})})})};
west.foo=function(a){a=a==null?resource_request_jsonstore.getKeyPairsListTree:a;this.tree=new Ext.tree.TreePanel({loader:new Ext.tree.TreeLoader,width:200,height:300,rootVisible:!1,border:!1,renderTo:Ext.get("keys_tree"),root:new Ext.tree.AsyncTreeNode({expanded:!0,leaf:!1,text:"Tree Root",children:a})})};
